// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hotel_management_api.Database;

#nullable disable

namespace hotel_management_api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230529040731_version_0.5")]
    partial class version_05
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("hotel_management_api.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CheckoutTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HotelRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserCreateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("hotel_management_api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CitizenIdentification")
                        .HasColumnType("longtext");

                    b.Property<byte>("CustomerType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberBooking")
                        .HasColumnType("int");

                    b.Property<string>("NumberPhone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("hotel_management_api.Models.HotelRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NoRoom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberBed")
                        .HasColumnType("int");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<byte>("RoomStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("RoomType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("hotel_rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 28,
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(5434),
                            Description = "",
                            Floor = 2,
                            Image = "",
                            NoRoom = "201",
                            NumberBed = 1,
                            Option = "",
                            Price = 3000000.0,
                            RoomStatus = (byte)0,
                            RoomType = (byte)0,
                            Size = "7mx4m",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Area = 40,
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(5440),
                            Description = "",
                            Floor = 2,
                            Image = "",
                            NoRoom = "202",
                            NumberBed = 2,
                            Option = "",
                            Price = 5000000.0,
                            RoomStatus = (byte)0,
                            RoomType = (byte)1,
                            Size = "8mx5m",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Area = 35,
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(5443),
                            Description = "",
                            Floor = 2,
                            Image = "",
                            NoRoom = "203",
                            NumberBed = 1,
                            Option = "",
                            Price = 3000000.0,
                            RoomStatus = (byte)0,
                            RoomType = (byte)2,
                            Size = "7mx5m",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Area = 28,
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(5444),
                            Description = "",
                            Floor = 3,
                            Image = "",
                            NoRoom = "301",
                            NumberBed = 1,
                            Option = "",
                            Price = 3000000.0,
                            RoomStatus = (byte)0,
                            RoomType = (byte)0,
                            Size = "7mx4m",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Area = 40,
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(5446),
                            Description = "",
                            Floor = 3,
                            Image = "",
                            NoRoom = "302",
                            NumberBed = 2,
                            Option = "",
                            Price = 5000000.0,
                            RoomStatus = (byte)0,
                            RoomType = (byte)1,
                            Size = "8mx5m",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Area = 35,
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(5448),
                            Description = "",
                            Floor = 3,
                            Image = "",
                            NoRoom = "303",
                            NumberBed = 1,
                            Option = "",
                            Price = 3000000.0,
                            RoomStatus = (byte)0,
                            RoomType = (byte)2,
                            Size = "7mx5m",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Area = 28,
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(5449),
                            Description = "",
                            Floor = 4,
                            Image = "",
                            NoRoom = "401",
                            NumberBed = 1,
                            Option = "",
                            Price = 3000000.0,
                            RoomStatus = (byte)0,
                            RoomType = (byte)0,
                            Size = "7mx4m",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Area = 40,
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(5451),
                            Description = "",
                            Floor = 4,
                            Image = "",
                            NoRoom = "402",
                            NumberBed = 2,
                            Option = "",
                            Price = 5000000.0,
                            RoomStatus = (byte)0,
                            RoomType = (byte)1,
                            Size = "8mx5m",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Area = 35,
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(5453),
                            Description = "",
                            Floor = 4,
                            Image = "",
                            NoRoom = "403",
                            NumberBed = 1,
                            Option = "",
                            Price = 3000000.0,
                            RoomStatus = (byte)0,
                            RoomType = (byte)2,
                            Size = "7mx5m",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("hotel_management_api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CitizenIdentification")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            CitizenIdentification = "001201030041",
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(4592),
                            DateOfBirth = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nguyenvana@gmail.com",
                            Name = "Nguyễn Văn A",
                            NumberPhone = "0123456789",
                            Password = "68F5F844896EE7A4626DA5678045EC26",
                            Role = "Manager",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "nguyenvana@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hà Nội",
                            CitizenIdentification = "001201030041",
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(4832),
                            DateOfBirth = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nguyenthib@gmail.com",
                            Name = "Nguyễn Thị B",
                            NumberPhone = "0123456788",
                            Password = "FF9AA1E68A37C1F87F9BE3B91860726A",
                            Role = "Accountant",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "nguyenthib@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Hà Nội",
                            CitizenIdentification = "001201030041",
                            CreatedDate = new DateTime(2023, 5, 29, 4, 7, 30, 879, DateTimeKind.Utc).AddTicks(4868),
                            DateOfBirth = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nguyenthib@gmail.com",
                            Name = "Nguyễn Thị B",
                            NumberPhone = "0123456788",
                            Password = "FF9AA1E68A37C1F87F9BE3B91860726A",
                            Role = "Receptionist",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "nguyenthib@gmail.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
